### PR TITLE
Always enable GTID in setup script

### PR DESCRIPTION
**Pull request by dbussink**
We have several services that are using GTIDs in production, so the local development environment should match this.

### CODE REVIEW

**Comment by dbussink** [comment]
@mistydemeo Is this something that could be merged? I continue to run into the issue that my local MySQL config is reset and this config is lost.

**Comment by ggunson** [comment]
@dbussink please cc @github/database-infrastructure when requesting homebrew mysql changes, we like to keep track. 

Since binary logging wasn't enabled anyways this wasn't necessary before, but if you're querying GTID values in code I guess it's a necessity now.

The settings look fine, glad to see `expires_logs_days` set. Wonder if the extra disk IO will have an effect on testing.

**Comment by ggunson** [comment]
On second thought, adding GTIDs and binary logging to default installs is not a simple thing to do, as these add restrictions of use.

https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html

e.g.
- can't mix MyISAM and InnoDB tables in the same transaction (you shouldn't anyways, but still)
- can't do "CREATE TABLE ... SELECT" anymore
- can't use temporary tables inside transactions
- issues with mysqldump if you go from gtid to not gtid
- etc.

The default binlog_format for newer 5.7 installs is "ROW", but if someone's using an older 5.7 or has a setting of "STATEMENT" or "MIXED" their error log could get spammed with [unsafe for replication statements](https://dev.mysql.com/doc/refman/5.7/en/replication-rbr-safe-unsafe.html).

If they need to turn GTID off manually on a MySQL instance they don't want to restart, they have to run these statements in order:

```
set global gtid_mode=ON_PERMISSIVE;
set global gtid_mode=OFF_PERMISSIVE;
set global gtid_mode=OFF;
set global enforce_gtid_consistency=OFF;
```
(see https://dev.mysql.com/doc/refman/5.7/en/replication-mode-change-online-disable-gtids.html)

With this plus extra disk usage, there is the potential for new problems and a reduction in accepted MySQL functionality.

**Comment by ggunson** [comment]
This can be closed since the changes were merged elsewhere.

**Pull request closed without merging**
