### PR TITLE
kind 0.3.0

### PR DESCRIPTION
**Pull request by mistydemeo**
/cc @Raffo, @jnewland

### CODE REVIEW

**Comment by jnewland** [comment]
Nice thanks @mistydemeo! Can you help me figure out how to install this locally to test it? I've never done this with homebrew! Thanks!

**Comment by mistydemeo** [comment]
If you've already tapped this repository, just `brew install kind`. Otherwise, you can use the fully-qualified name to add the repository and install it in one step: `brew install github/bootstrap/kind`.

**Comment by jnewland** [comment]
Hmm! `brew install github/bootstrap/kind` didn't work for me:

```
Error: No available formula with the name "github/bootstrap/kind" 
==> Searching for a previously deleted formula (in the last month)...
Warning: github/bootstrap is shallow clone. To get complete history run:
  git -C "$(brew --repo github/bootstrap)" fetch --unshallow
```

Is there perhaps something I need to do to configure homebrew to look at the `add_kind` branch?

**Comment by mistydemeo** [comment]
Oh of course, because this isn't in master. Blanked on that.

First do `git -C "$(brew --repo github/bootstrap)" checkout add_kind`, then `brew install github/bootstrap/kind`. You can change the branch back to master after.

**Pull request merged**
