### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- Fix various RuboCop warnings
- Avoid using non-`HOMEBREW_` environment variables as they will be shortly filtered out by Homebrew itself.
- Remove Boxen compatibility layer.

CC @mistydemeo @github/dx for review

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks for review, @mistydemeo!

**Comment by phantomdata** [comment]
:wave: @MikeMcQuaid It looks like the introduction of the `<<~` around https://github.com/github/homebrew-bootstrap/commit/d2251b05bcdcb5bc68831ecc91553f37b76b1590#diff-0049c90989a3db3763e917d526e446faR20 and a few other places broke this for Ruby 2.1.  We discovered this while testing a new Halp change.  :) . Do you want to undo this or should we (Embedded Tools)?  Just don't want to step on any toes by undoing your changes.  :)

**Comment by MikeMcQuaid** [comment]
@phantomdata Can you elaborate on how/where this is broken and how to reproduce? Homebrew is run with (and includes a vendored) Ruby 2.3 so it should be considered a 🐛 in these scripts if they are ever being run with Ruby 2.3.

**Comment by phantomdata** [comment]
Oh hey there; so when attempting to run Halp's `script/bootstrap` we now get the following error:

```
/usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap/cmd/brew-setup-nginx-conf:50: syntax error, unexpected ':', expecting keyword_end
    Error: Homebrew is not in /usr/local. Install it by running Strap:
          ^
/usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap/cmd/brew-setup-nginx-conf:50: syntax error, unexpected keyword_in, expecting '('
    Error: Homebrew is not in /usr/local. Install it by running Strap:
                             ^
/usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap/cmd/brew-setup-nginx-conf:50: unknown regexp options - lcal
/usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap/cmd/brew-setup-nginx-conf:55: syntax error, unexpected <<
brewfile = <<~EOS
```

It does look like Halp is [rebinding rbexec](https://github.com/github/halp/blob/master/script/bootstrap#L20), which might be where its taking over from the vendored Ruby.  See anything obvious there?

**Comment by MikeMcQuaid** [comment]
@phantomdata @rufo Apologies, fixed in https://github.com/github/homebrew-bootstrap/pull/43.

**Pull request merged**
